### ISSUE TITLE
`using` type aliases are C++11, not C++03.

### ISSUE THREAD

**Issue by jrlanglois** [PollardBanknote/cppbackport#6]
Example:

https://github.com/PollardBanknote/cppbackport/blob/master/lib/traits/add_cv.h#L53-L59

**Comment by jlee975** [comment]
I had a quick look and all instances seem to be in "C++11, but not C++14" code, which is fine. As far as I know, there is no way to implement those particular cases in C++03 (i.e., the type_trait_t helpers)
