### ISSUE TITLE
is_member_object_pointer should be is_member_object_pointer_v

### ISSUE THREAD

**Issue by jrlanglois** [PollardBanknote/cppbackport#9]
https://github.com/PollardBanknote/cppbackport/blob/master/lib/traits/is_member_pointer.h#L91

See this for more details:
http://en.cppreference.com/w/cpp/types/is_member_object_pointer

**Comment by jlee975** [comment]
Fixed with 26f7c7b054807cb8f8607383af3c831bd356d6cb
